version: '3.7'

services:
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    volumes:
      - type: bind
        source: ./wiremock
        target: /home/wiremock
    command: --port=8090 --global-response-templating --verbose
    ports:
      - "8090:8090"